

# name: 'Hello World78601-56'
#  description: 'Trigger APIsec scan'
#  inputs:
#    apisec-username:
#      description: 'The APIsec username with which the scans will be executed'
#      required: true

#    apisec-password:
#      description: 'The Password of the APIsec user with which the scans will be executed'
#      required: true

#    apisec-scan-job:  
#      description: 'The id of the scan job to run'
#      required: true

#    apisec-region:  
#      description: 'The location the scan will be executed in'
#      required: true
#      default: 'SUPER_1'
#    apisec-environment:  
#      description: 'The id of the environment to run'
#      required: true
  
#    apisec-project:
#      description: 'The id of the project for security scan'
#      required: true


# runs:
#    using: "composite"
#    steps: 
#      - run: | 
#           wget https://raw.githubusercontent.com/intesar/FX-Scripts/master/fx_job_invoke_script.sh?token=AElo1orWSWln6w6y5uX0-1ylzPH8TX_3ks5bqJBywA%3D%3D -O fx_job_invoke_script.sh;bash fx_job_invoke_script.sh ${{inputs.apisec-username}} ${{ inputs.apisec-password }} ${{ inputs.apisec-project }} ${{ inputs.apisec-region }} ${{ inputs.apisec-environment }} ${{ inputs.apisec-scan-job }}
#        shell: bash



# name: 'APIsec Playbook Regeneration'
# description: 'Continuous, automated, comprehensive API Security Testing'
# inputs:
#   apisec-username:
#     description: 'The APIsec username with which the scans will be executed'
#     required: true
#     default: ''
#   apisec-password:
#     description: 'The Password of the APIsec user with which the scans will be executed'
#     required: true
#     default: '' 
#   apisec-projectname:
#     description: 'The Name of the project for security scan'
#     required: true
#     default: ''
#   apisec-profile:  
#     description: 'The Name of the scan profile to be executed'
#     required: false
#     default: 'Master'
#   apisec-region:  
#     description: 'The location the scan will be executed in'
#     required: false
#     default: ''
#   sarif-result-file:  
#     description: 'The path to the sarif format result file'
#     required: false
#     default: ''
#   apisec-host:
#     description: 'APIsec host url'
#     required: false
#     default: 'https://cloud.apisec.ai'
#   apisec-emailReport:
#     description: 'Whether to send report's email'
#     required: false
#     default: false
#   apisec-reportType:
#     description: 'Type of Report to be email'
#     required: false
#     default: 'RUN_SUMMARY'

# runs:
#   using: "composite"
#   steps:
#     - run:  ${GITHUB_ACTION_PATH}/apisec_playbooks_regenerate_scan_trigger.sh "${{inputs.apisec-host}}" "${{inputs.apisec-username}}" "${{ inputs.apisec-password }}" "${{ inputs.apisec-projectname }}" "${{ inputs.apisec-profile }}" "${{ inputs.apisec-region }}" "${{ inputs.sarif-result-file }}" "${{ inputs.apisec-emailReport }}"  "${{ inputs.apisec-reportType }}"
#       shell: bash


 name: 'SECURITY-RUN-SCANNER'
 description: 'Trigger APIsec scan'
 inputs:
   apisec-username:
     description: 'The APIsec username with which the scans will be executed'
     required: true
     default: ''
   apisec-password:
     description: 'The Password of the APIsec user with which the scans will be executed'
     required: true
     default: ''  
   apisec-scan-job:  
     description: 'The id of the scan job to run'
     required: true
     default: ''
   apisec-region:  
     description: 'The location the scan will be executed in'
     required: true
     default: 'SUPER_1'
   apisec-environment:  
     description: 'The id of the environment to run'
     required: true
     default: ''
   apisec-project:
     description: 'The id of the project for security scan'
     required: true
     default: ''
 runs:
   using: "composite"
   steps:
     - run: | 
           wget https://raw.githubusercontent.com/intesar/FX-Scripts/master/fx_job_invoke_script.sh?token=AElo1orWSWln6w6y5uX0-1ylzPH8TX_3ks5bqJBywA%3D%3D -O fx_job_invoke_script.sh;bash fx_job_invoke_script.sh ${{inputs.apisec-username}} ${{ inputs.apisec-password }} ${{ inputs.apisec-project }} ${{ inputs.apisec-region }} ${{ inputs.apisec-environment }} ${{ inputs.apisec-scan-job }}
       shell: bash


# # name: 'Hello World78601'
# name: 'Test-Pacbot-Scanner'
# description: 'Trigger APIsec scan'
# inputs:
#   apisec-username:
#     description: 'The APIsec username with which the scans will be executed'
#     required: true

#   apisec-password:
#     description: 'The Password of the APIsec user with which the scans will be executed'
#     required: true

#   apisec-scan-job:  
#     description: 'The id of the scan job to run'
#     required: true

#   apisec-region:  
#     description: 'The location the scan will be executed in'
#     required: true
#     default: 'SUPER_1'
#   apisec-environment:  
#     description: 'The id of the environment to run'
#     required: true
  
#   apisec-project:
#     description: 'The id of the project for security scan'
#     required: true
# runs:
#   using: "composite"
#   steps:
#     - run: | 
#           wget https://raw.githubusercontent.com/intesar/FX-Scripts/master/fx_job_invoke_script.sh?token=AElo1orWSWln6w6y5uX0-1ylzPH8TX_3ks5bqJBywA%3D%3D -O fx_job_invoke_script.sh;bash fx_job_invoke_script.sh ${{inputs.apisec-username}} ${{ inputs.apisec-password }} ${{ inputs.apisec-project }} ${{ inputs.apisec-region }} ${{ inputs.apisec-environment }} ${{ inputs.apisec-scan-job }}
#       shell: bash



# name: 'Hello World78601'
# description: 'Trigger APIsec scan'
# inputs:
#   apisec-username:
#     description: 'The APIsec username with which the scans will be executed'
#     required: true

#   apisec-password:
#     description: 'The Password of the APIsec user with which the scans will be executed'
#     required: true

#   apisec-scan-job:  
#     description: 'The id of the scan job to run'
#     required: true

#   apisec-region:  
#     description: 'The location the scan will be executed in'
#     required: true
#     default: 'SUPER_1'
#   apisec-environment:  
#     description: 'The id of the environment to run'
#     required: true
  
#   apisec-project:
#     description: 'The id of the project for security scan'
#     required: true
#   who-to-greet:  # id of input
#     description: 'Welcome to hyderabad'
#     required: true
#      default: 'Welcome to Hyderabad World!!!!'

# outputs:
#    random-number:
#      description: "Random number"
#      value: ${{ steps.who-to-greet }}    

# runs:
#    using: "composite"
#   steps:
#      - run: echo Hello ${{ inputs.who-to-greet }}.
#        shell: bash
  
#     - run: | 
#          wget https://raw.githubusercontent.com/intesar/FX-Scripts/master/fx_job_invoke_script.sh?token=AElo1orWSWln6w6y5uX0-1ylzPH8TX_3ks5bqJBywA%3D%3D -O fx_job_invoke_script.sh;bash fx_job_invoke_script.sh ${{inputs.apisec-username}} ${{ inputs.apisec-password }} ${{ inputs.apisec-project }} ${{ inputs.apisec-region }} ${{ inputs.apisec-environment }} ${{ inputs.apisec-scan-job }}
#       shell: bash
